mogd optimization
Angryrou/udao pull request #9
Opened 2023-12-26 03:02 UTC by Angryrou

2023-12-26 03:02 UTC, Angryrou commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Angryrou/udao/9?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `dev`
  * **PR #6** <a href="https://app.graphite.dev/github/pr/Angryrou/udao/6?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #9** <a href="https://app.graphite.dev/github/pr/Angryrou/udao/9?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Angryrou/udao/9?utm_source=stack-comment).

2023-12-27 10:54 UTC, julhien requested changes
To avoid handling specific cases in MOGD, and to make the unique computation of embeddings available in all solvers, I suggest to store the value of the embedding within the derived model and not worry about it in the solver itself.

```python

class FixedEmbeddingUdaoModel(th.nn.Module):
    def __init__(self, model: UdaoModel, embedding: Optional[th.Tensor] = None) -> None:
        super().__init__()
        self.model = model
        self.embedding = embedding

    def forward(
        self, input_data: UdaoEmbedInput
    ) -> th.Tensor:
        if embedding is None:
            self.embedding = self.embedder(input_data.embedding_input)
        return self.model(input_data, self.embedding)
```

2023-12-27 14:47 UTC, julhien commented on udao/optimization/soo/mogd.py
> +        input_data : Union[UdaoInput, List, Dict]
```suggestion
        input_data : Union[UdaoInput, Dict]
```

2023-12-27 14:47 UTC, julhien commented on udao/optimization/soo/mogd.py
> +            - List: [UdaoEmbedInput, embedding: th.Tensor]
```suggestion
```

2023-12-27 14:47 UTC, julhien commented on udao/optimization/soo/mogd.py
> +                    else input_data,
```suggestion
                    input_data,
```

2023-12-27 14:47 UTC, julhien commented on udao/model/model.py
> +class FixedEmbeddingUdaoModel(th.nn.Module):
```suggestion
class FixedEmbeddingUdaoModel(th.nn.Module):
"""
Assumes the embedding part does not change between inputs and caches it after computing it once. This is relevant for an optimization pipeline where the embedding input (e.g. a query plan) is a fixed parameter
"""
```

2023-12-27 15:21 UTC, julhien approved these changes

2023-12-27 15:22 UTC, merged